on: [push, pull_request]
name: Test

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Tools
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest

    - name: Build
      run: go build main.go
    - name: Vet
      run: go vet ./...
    - name: Secure
      run: gosec ./...
    - name: Test
      run: go test ./... -v